Adds basic musicxml lyric support
helge17/tuxguitar pull request #282
Opened 2024-03-14 17:02 UTC by profOnno

Adds basic musicxml lyric support

my notes on the state machine:
[Quick sheets.pdf](https://github.com/helge17/tuxguitar/files/14605513/Quick.sheets.pdf)

Not sure about the naming of my methods and classes.

In the `getLyricSlice` function I'm using `Arrays.stream`,  the are other ways to do this if this is only supported in newer Java versions.

I did add javadoc compatible comments. I let it generate in `doc/java_docs` but the config for this is not in this request.

Take your time with the review. Java is a language I didn't touch in a decade, so there are probably better ways to do some things.

Cheers,

Menno

2024-03-14 19:33 UTC, guiv42 commented
Thanks for the contribution!

> Not sure about the naming of my methods and classes.

No problem. Nobody can be sure of anything, since there's no such thing as coding rules or naming conventions. We'll need to do this one day.

> Now it will export the lyrics twice, to the main track and to the tablature. Not sure about this, maybe only on the main track is better.

I've got to test this, but intuitively I would think only the main track would be more readable.

> Take your time with the review. Java is a language I didn't touch in a decade, so there are probably better ways to do some things.

I'm definitely no java expert. So the added value of my review should be limited to the interactions of your code with other parts/modules of TuxGuitar. I can also do some testing, but not much more.

2024-03-15 22:33 UTC, guiv42 reviewed
I find the result is really good, great job, thanks!

As you see, my remarks are essentially formal, I only suggest minor modifications.
Exporting lyrics only with score (and not with tablature) seems to me the only significant evolution.
And could you please re-indent the 2 files? (e.g. several lines with useless tabs at end of line)

(by the way, when testing your modification I detected a bug already present before: tab shall not be exported for drums track. I will fix this after this PR is merged)

2024-03-15 22:33 UTC, guiv42 commented on desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLLyricWriter.java
> +	      : (string.substring(0, string.length() - 1));
minor remark: this could be re-indented (replace leading spaces with tabs)

2024-03-15 22:33 UTC, guiv42 commented on desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java
> +		int lyricFrom = track.getLyrics().getFrom();
unused variable, can be deleted

2024-03-15 22:33 UTC, guiv42 commented on desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java
> +					writeLyric(noteNode, measureLyric);
as suggested in your PR, I think exporting lyrics only under score (and not under tablature) makes the result more readable. Just adding a condition `if (!isTablature)` should do the job.

2024-03-15 22:33 UTC, guiv42 commented on desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLLyricWriter.java
> +		//track = _track; // do we have to specify this?
is this question still open? It seems it isn't, so I think this line can be deleted

2024-03-15 22:33 UTC, guiv42 commented on desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLLyricWriter.java
> +		// or keep the lyric "", and filter out in write beats
Actual result seems pretty good, I would not change it.

2024-03-15 22:33 UTC, guiv42 commented on desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLLyricWriter.java
> +		//measureLyricArray = (MusicXMLMeasureLyric[]) measureLyrics.toArray();
this line can be deleted

2024-03-16 08:55 UTC, profOnno commented
Thank you for the review. I agree with your remarks, and will adjust the code accordingly.

2024-03-18 09:41 UTC, profOnno commented on desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java
> +					writeLyric(noteNode, measureLyric);
Changing this (wait for the pull). There was a bug when using chords. The new code will show this. So the lyric will be attached to the first note on a chord, or just on the note if there is no chord.

2024-03-18 11:54 UTC, profOnno commented
Pfff... Trying to understand the git workflow to rebase is hard work :sweat_smile:.
But I think it worked.

2024-03-18 23:03 UTC, guiv42 requested changes
See my comment, it fixes issue.

2024-03-18 23:03 UTC, guiv42 commented on desktop/TuxGuitar-musicxml/src/org/herac/tuxguitar/io/musicxml/MusicXMLWriter.java
>  					if(n > 0){
replace lines 344 to 360 by this code:

```
					if(n > 0){
						this.addNode(noteNode,"chord");
					}
					
					Node pitchNode = this.addNode(noteNode,"pitch");
					this.writeNote(pitchNode, "", value, ks);
					this.writeDuration(noteNode, voice.getDuration(), note.isTiedNote());
					
					if ((n==0) && !isTablature) {
						// Attach lyric to the first note
						try {
							MusicXMLMeasureLyric measureLyric = lyrics[lyricIndex++];
							writeLyric(noteNode, measureLyric);
						} catch (Exception e) {
							// ignore
							// can be out of bound? when there are more lyrics than text
							// can be null if there is an offset
						}
					}
```

2024-03-19 15:15 UTC, profOnno commented
Did it a little bit different but it passed the xmllint. Now without rebase. Thanks for the explanation on how to do this.
I'll try to add xmllint in the test maven test, in a new pull request (if I get it working)

2024-03-19 17:17 UTC, guiv42 commented
> Did it a little bit different but it passed the xmllint.

It's ok now, thanks.

> Do you have a blueprint of how to add a test? I added a test folder in next to the src and used eclipse to add a junit test.

No, but I would really like to, that's yet another thing I have to learn. I introduced the first tests in the code base recently, without a clear knowledge of the correct way to do it, so it's definitely not clean. If you can find how to do that, I will refactor org.herac.tuxguitar.test package.

2024-03-19 17:17 UTC, merged