Configurable tuning presets in xml file using priority attributes
helge17/tuxguitar pull request #304
Opened 2024-03-22 04:55 UTC by tdan

- Add an optional attribute priority to tuning presets in tuning.xml file
- Add an integer attribute priority in TGTuning class, with value imported from xml file content
- Implement Comparable<TGTuning> interface in TGTuning class, so instances can be sorted by priority order
- Add method getPrioritizedTgTunings(), which returns all TG tuning presets with a defined priority attribute, discard tuning presets with no priority.

2024-03-22 21:09 UTC, guiv42 requested changes
Okay, there are quite a few blocking items here

1. The most critical one: only modify the minimum set of files required to implement the expected evolution. Especially do **not** modify `.gitignore`. In this case, I just cannot run the app from your branch (it builds but fails to start). Also it hides probably some modifications that you have done in other parts of the code base.
Basically for this evolution, modifying *only* these files should do the job: TuningManager.java, TuningReader.java, TGTuning.java, MidiSongReader.java, tunings.xml. No less, no more.
I don't know why the scope of your modifications was wider. Don't hesitate to ask for support if needed.
2. don't push from your master branch. In case your pull request is not merged (like this one), you will need to re-synchronize your master branch. And please squash your commits before submitting a PR (the intermediate steps of your development should not appear in main branch history). One classical way to do this:
- from master branch, create 2 branches : "feature" (here 269) and "dev"
- work in your "dev" branch, with as many commits as you like
- when you're ready, `merge squash` "dev" into "feature", and push "feature" branch to create PR. So in your PR, only one commit appears.

3. Please don't break indentation, this makes the code unreadable

4. About the functional evolution: most of the job is correctly done, except the last part (midi import) where the added value is expected. Objective of this issue is to remove redundancy between java code and xml, yet it is still present. See my comments in MidiFileReader, this should be easy to fix I think. All the other modified files are OK :)

So, this PR cannot be merged. But there's not much job to do to make this acceptable. Here's the best way to go forward I think:
- do not try to update this PR, there are some modifications in the commit history that I don't want to appear in master's history
- create a new branch (or 2 as suggested above) from the last version of master
- copy into this branch the few modified files listed above
- apply in MidiFileReader the required correction
- create a new PR

2024-03-22 21:09 UTC, guiv42 commented on .gitignore
> +desktop/build-scripts/*
Blocking point, these build scripts are key assets, it's not possible to exclude them from configuration management.
For such a functional modification, there's no reason to change .gitignore file

Additional reason: I fetched a copy of your branch, and I cannot run this version. Most probably there's a conflict with master branch on build scripts...

2024-03-22 21:09 UTC, guiv42 commented on desktop/TuxGuitar/src/org/herac/tuxguitar/app/view/dialog/about/TGAboutDialog.java
> +	private static final String RELEASE_NAME = (TGApplication.NAME + " 2024-03-12-Issue#269");
This file shall not be modified, version is propagated by a script during release delivery process.

2024-03-22 21:09 UTC, guiv42 commented on common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/xml/TuningReader.java
> +				System.out.print(group.getTunings().toString());
debug log ?
to be deleted

2024-03-22 21:09 UTC, guiv42 commented on common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/TuningManager.java
> -	static String TG_TUNING_FILE = "tunings" + File.separator + "tunings.xml";
please don't change indentation:
- as you can see, the complete file appears as modified, this makes code review much more complex for me!
- keep indentation rules as consistent as possible across all files from project, or else it's impossible for developers to correctly configure indentation rules in IDE.

2024-03-22 21:09 UTC, guiv42 commented on common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
> +                        // E Standard
please don't change indentation rules.
here, mix of spaces and tabs makes file not very readable

2024-03-22 21:09 UTC, guiv42 commented on common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
>  			if(this.minValue >= 40 && this.maxValue <= 64 + maxFret){
The idea here was to remove the hard-coded constants, which are still there. This code is still redundant with the content of the xml file.

At this stage, `tunings` variable contains a list of tunings, and it is possible to deduce the reachable range of notes from tuning properties.
So: delete lines 709 to 741, and replace by (pseudo code)
- for each tuning in tunings
  - loop over tuning.values, retrieve min and max values
  - if (this.minValue >= tuningMinValue && this.maxValue <= tuningMaxValue+maxFret) { then do what's actually repeated 5 times and break loop}
- if, after loop ends, no tuning has been found, then execute lines 743 to 748

Objective: at the end, selection of tuning *only* relies on xml file content. No more hard-coded constants.

2024-03-23 04:03 UTC, tdan commented
Hey @guiv42 I really appreciate your feedback! This is my first PR ever so I have a lot of things to learn :).

Gonna work on it ASAP.

2024-03-23 07:49 UTC, closed without merging