Configurable tuning presets in xml file using priority attributes
helge17/tuxguitar pull request #319
Opened 2024-04-03 04:42 UTC by tdan

modified:   common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/TuningManager.java
	modified:   common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/xml/TuningReader.java
	modified:   common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGTuning.java
	modified:   common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
	modified:   desktop/TuxGuitar/share/tunings/tunings.xml

2024-04-03 22:28 UTC, guiv42 requested changes
Still a few remarks to consider, one more iteration should be enough.
You can just push a new commit in your PR-ready branch
#269

2024-04-03 22:28 UTC, guiv42 commented on common/TuxGuitar-lib/src/org/herac/tuxguitar/song/helpers/tuning/TuningManager.java
> +
Revert this modification.
It's the role of TGResourceManager to manage the path to resources, it shall **not** be redefined here.

The problem is in MidiSongReader:  you are providing a new (blank) context to TuningManager (see remark below, in MidiSongReader line 705)

2024-04-03 22:28 UTC, guiv42 commented on common/TuxGuitar-lib/src/org/herac/tuxguitar/song/models/TGTuning.java
> +		return (minVal >= values[values.length - 1]) && (maxVal <= values[0]);
need to loop over all values, to check *all of them* are in range.
It is not impossible that strings are not sorted by values, some people use weird tunings!

2024-04-03 22:28 UTC, guiv42 commented on common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
> +			for (TGTuning tuning : tunings)
I know there is no coding style rule established, but please add explicit { and } in the `for` loop:
```
for (TGTuning : tunings) {
   do the stuff here;
}
```

2024-04-03 22:28 UTC, guiv42 commented on common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
> +			TuningManager tuningManager = TuningManager.getInstance(new TGContext());
Here, you are redefining a new instance of TuningManager, because you're recreating it from a *new context*.
This is why you needed to modify TuningManager, and to redefine the path to the resource (see remark in TuningManager file). With this blank context, the resource manager is missing information to find the resource...
I had not anticipated this. How to retrieve the correct context:

In MidiSongReader, add a property `private TGContext context`
Set this property in constructor:
```
	public MidiSongReader(TGContext context) {
		super();
		this.context = context;
	}
```

When retrieving TuningManager instance, use `this.context` as a parameter instead of `new TGContext()`

In class `MidiSongReaderPlugin`, add the `context` parameter when creating instance of MidiSongReader:
```
	protected TGSongReader createInputStream(TGContext context) throws TGPluginException {
		return new MidiSongReader(context);
	}
```

2024-04-08 04:02 UTC, tdan commented on common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
> +			TuningManager tuningManager = TuningManager.getInstance(new TGContext());
Hey this is awesome! Yeah, I didn't know how to retrieve the correct context in the first place so that was my work-around to get the program run.

By the way, I noticed `tuningManager` would get called and had to load and process the same xml resource on every track. Would it be better to add a property `private TuningManager tuningManager` in MidiSongReader, and initialize it only once in the constructor?
 
`
public TrackTuningHelper(int track) { 
	this.track = track;
	this.maxValue = -1;
	this.minValue = -1;
	this.tuningManager = TuningManager.getInstance(MidiSongReader.this.context);
}
`

`
List<TGTuning> tunings = this.tuningManager.getPriorityTgTunings();
`

2024-04-08 17:48 UTC, guiv42 commented on common/TuxGuitar-midi/src/org/herac/tuxguitar/io/midi/MidiSongReader.java
> +			TuningManager tuningManager = TuningManager.getInstance(new TGContext());
> I noticed tuningManager would get called and had to load and process the same xml resource on every track.

It's because you're not providing the correct context.

>  Would it be better to add a property private TuningManager tuningManager in MidiSongReader, and initialize it only once in the constructor?

No. Just provide the correct context, then you will see that TuningManager.loadTunings is only called once.

2024-04-09 19:03 UTC, merged