Update Polish Translation
helge17/tuxguitar pull request #505
Opened 2024-09-06 07:31 UTC by Gootector

Update Polish Translation

Greetings,
Gootector

2024-09-07 12:33 UTC, guiv42 commented on android/TuxGuitar-android/res/values-b+pl/strings.xml
> +	<string name="action_transport_play">Odtwarzaj/wstrzymaj utwór</string>
@Gootector : please don't modify android `string.xml` file. These files are generated from the files in `common/resources` before release.
See here:
https://github.com/helge17/tuxguitar/blob/647c7826acbfa11ad0a551480192f52815b1b8a6/android/TuxGuitar-android/res/values-b%2Bpl/strings.xml#L5

2024-09-07 12:34 UTC, guiv42 requested changes
see my comment: android translation files shall not be modified manually

2024-09-07 16:03 UTC, Gootector commented
> see my comment: android translation files shall not be modified manually

If it is as you typed here, it will be generated automatically. My changes will be replaced (or not) and I don't have to do anything with this PR. Please merge my PR. Thank you.

2024-09-07 16:17 UTC, closed without merging

2024-09-07 19:51 UTC, guiv42 commented
Well, that's right, I could have merged it...
Thanks for the update

2024-09-07 21:08 UTC, Gootector commented
> Well, that's right, I could have merged it... Thanks for the update

https://github.com/helge17/tuxguitar/commits/master/android/TuxGuitar-android/res/values-b%2Bpl - As you can see, the last changes (PR) before 1.6.4 release are made by me. No "generate from the files in common/resources before release"?

2024-09-08 09:21 UTC, guiv42 commented
Hmm, that's annoying.
The script to generate android translations from "common" files is [there](https://github.com/helge17/tuxguitar/blob/master/misc/messages_desktop_to_android.pl). The problem is that it's not automatized yet, so it's possible to forget this step before releasing.
I don't know what's best here. It seems difficult to me to ask all translators to run this perl script by themselves. We've got to think at a better solution.

2024-09-10 16:44 UTC, helge17 commented
The build script now checks if the Android translations are up to date when releasing a new stable version (8af678c32f238a1c4ad9e553cd03ca67cc5161b7).